import unittest
import exam


class test_read_exam():
    '''test function read_exam'''
    qns, qts, ias = exam.read_exam(inter=False)
    assert(len(qns) == len(qts) == len(ias))
    assert(isinstance(qns[1], int))

    print('\n## Ran read_exam with simulated inputs; test passed')


class test_make_answers(unittest.TestCase):
    '''test function make_answers'''
    QUESTIONS, QUESTION_TEXTS, ANSWERS,\
        MY_ANSWERS, MY_ANSWERS_JS = exam.make_answers(inter=False)
    assert(len(QUESTIONS) == 11)
    assert(len(QUESTION_TEXTS) == 11)
    assert(len(ANSWERS) == 11)
    assert(len(MY_ANSWERS) == 11)
    assert(isinstance(MY_ANSWERS_JS, str))
    print(MY_ANSWERS_JS)

    print('## Loaded pickle generated by read_exam; test passed')
